export const LAST_NEWS_REQUEST = "LAST_NEWS_REQUEST"
export const LAST_NEWS_SUCCESS = "LAST_NEWS_SUCCESS"
export const LAST_NEWS_FAILURE = "LAST_NEWS_FAILURE"

export const LAST_POSTS_REQUEST = "LAST_POSTS_REQUEST"
export const LAST_POSTS_SUCCESS = "LAST_POSTS_SUCCESS"
export const LAST_POSTS_FAILURE = "LAST_POSTS_FAILURE"