export const USERS_REQUEST = "USERS_REQUEST"
export const USERS_SUCCESS = "USERS_SUCCESS"
export const USERS_FAILURE = "USERS_FAILURE"

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE"

