export const USERS_REQUEST = "USERS_REQUEST"
export const USERS_SUCCESS = "USERS_SUCCESS"
export const USERS_FAILURE = "USERS_FAILURE"

export const LAST_POSTS_REQUEST = "LAST_POSTS_REQUEST"
export const LAST_POSTS_SUCCESS = "LAST_POSTS_SUCCESS"
export const LAST_POSTS_FAILURE = "LAST_POSTS_FAILURE"
